<?php

$permissionArr = [
    "user" => [
        "user_create",
        "user_update",
        "user_delete",
        "user_read",
        "user_status",
        "user_terminal",
    ],
    "language" => [
        "language_create",
        "language_update",
        "language_delete",
        "language_read",
        "language_status",
    ],
    "translation" => [
        "translation_create",
        "translation_update",
        "translation_delete",
        "translation_read",
    ],
    "page" => [
        "page_create",
        "page_update",
        "page_delete",
        "page_read",
        "page_status",
    ],
    "seo" => [
        "seo_create",
        "seo_update",
        "seo_delete",
        "seo_read",
        "seo_status",
    ],
    "activity_log" => [
        "activity_log_create",
        "activity_log_update",
        "activity_log_delete",
        "activity_log_read",
        "activity_log_status",
    ],
    "permission" => [
        "permission_create",
        "permission_update",
        "permission_delete",
        "permission_read",
        "permission_status",
    ],
    "notification" => [
        "notification_create",
        "notification_update",
        "notification_delete",
        "notification_read",
        "notification_status",
    ],
    "complaint" => [
        "complaint_create",
        "complaint_update",
        "complaint_delete",
        "complaint_read",
        "complaint_status",
        "complaint_reply",
    ],
    "config" => [
        "config_create",
        "config_update",
        "config_delete",
        "config_read",
        "config_status",
        "config_monitoring",
    ],
    "comment" => [
        "comment_create",
        "comment_update",
        "comment_delete",
        "comment_read",
        "comment_status",
    ],
    "messaging" => [
        "messaging_create",
        "messaging_update",
        "messaging_delete",
        "messaging_read",
        "messaging_status",
        "messaging_view_message",
    ],
    "blocked_credential" => [
        "blocked_credential_create",
        "blocked_credential_update",
        "blocked_credential_delete",
        "blocked_credential_read",
        "blocked_credential_status",
    ],
    "category" => [
        "category_create",
        "category_update",
        "category_delete",
        "category_read",
        "category_status",
    ],
    "attribute" => [
        "attribute_create",
        "attribute_update",
        "attribute_delete",
        "attribute_read",
        "attribute_status",
    ],
    "terms" => [
        "terms_create",
        "terms_update",
        "terms_delete",
        "terms_read",
        "terms_status",
    ],
    "payment_service" => [
        "payment_service_create",
        "payment_service_update",
        "payment_service_delete",
        "payment_service_read",
        "payment_service_status",
    ],
    "payment" => [
        "payment_create",
        "payment_update",
        "payment_delete",
        "payment_read",
        "payment_status",
    ],
    "country" => [
        "country_create",
        "country_update",
        "country_delete",
        "country_read",
        "country_status",
    ],
    "city" => [
        "city_create",
        "city_update",
        "city_delete",
        "city_read",
        "city_status",
    ],
    "region" => [
        "region_create",
        "region_update",
        "region_delete",
        "region_read",
        "region_status",
    ],
    "subway" => [
        "subway_create",
        "subway_update",
        "subway_delete",
        "subway_read",
        "subway_status",
    ],
    "advertisement" => [
        "advertisement_create",
        "advertisement_update",
        "advertisement_delete",
        "advertisement_read",
        "advertisement_status",
    ],
    "service" => [
        "service_create",
        "service_update",
        "service_delete",
        "service_read",
        "service_status",
    ],
    "customer" => [
        "customer_create",
        "customer_update",
        "customer_delete",
        "customer_read",
        "customer_status",
    ],
"appointment" => [
        "appointment_create",
        "appointment_update",
        "appointment_delete",
        "appointment_read",
        "appointment_status",
    ],
    "clinic" => [
        "clinic_create",
        "clinic_update",
        "clinic_delete",
        "clinic_read",
        "clinic_status",
    ],
    "doctor" => [
        "doctor_create",
        "doctor_update",
        "doctor_delete",
        "doctor_read",
        "doctor_status",
    ],
    "patient" => [
        "patient_create",
        "patient_update",
        "patient_delete",
        "patient_read",
        "patient_status",
    ],
    "review" => [
        "review_create",
        "review_update",
        "review_delete",
        "review_read",
        "review_status",
    ],
];

return [
    "permissions" => $permissionArr,
    "roles" => [
        "user" => [],
        "admin" => $permissionArr,
    ]
];
