<?php

$permissionArr = [
    "user" => [
        "user_create",
        "user_update",
        "user_delete",
        "user_read",
        "user_status",
        "user_terminal",
    ],
    "language" => [
        "language_create",
        "language_update",
        "language_delete",
        "language_read",
        "language_status",
    ],
    "translation" => [
        "translation_create",
        "translation_update",
        "translation_delete",
        "translation_read",
    ],
    "page" => [
        "page_create",
        "page_update",
        "page_delete",
        "page_read",
        "page_status",
    ],
    "seo" => [
        "seo_create",
        "seo_update",
        "seo_delete",
        "seo_read",
        "seo_status",
    ],
    "activity_log" => [
        "activity_log_create",
        "activity_log_update",
        "activity_log_delete",
        "activity_log_read",
        "activity_log_status",
    ],
    "permission" => [
        "permission_create",
        "permission_update",
        "permission_delete",
        "permission_read",
        "permission_status",
    ],
    "notification" => [
        "notification_create",
        "notification_update",
        "notification_delete",
        "notification_read",
        "notification_status",
    ],
    "complaint" => [
        "complaint_create",
        "complaint_update",
        "complaint_delete",
        "complaint_read",
        "complaint_status",
        "complaint_reply",
    ],
"config" => [
        "config_create",
        "config_update",
        "config_delete",
        "config_read",
        "config_status",
        "config_monitoring",
    ],
    "comment" => [
        "comment_create",
        "comment_update",
        "comment_delete",
        "comment_read",
        "comment_status",
    ],
    "messaging" => [
        "messaging_create",
        "messaging_update",
        "messaging_delete",
        "messaging_read",
        "messaging_status",
        "messaging_view_message",
    ],
    "mail_template" => [
        "mail_template_create",
        "mail_template_update",
        "mail_template_delete",
        "mail_template_read",
        "mail_template_status",
    ],
    "mail_list" => [
        "mail_list_create",
        "mail_list_update",
        "mail_list_delete",
        "mail_list_read",
        "mail_list_status",
    ],
    "mail_campaign" => [
        "mail_campaign_create",
        "mail_campaign_update",
        "mail_campaign_delete",
        "mail_campaign_read",
        "mail_campaign_status",
    ],
    "mail_log" => [
        "mail_log_create",
        "mail_log_update",
        "mail_log_delete",
        "mail_log_read",
        "mail_log_status",
    ],
    "blocked_credential" => [
        "blocked_credential_create",
        "blocked_credential_update",
        "blocked_credential_delete",
        "blocked_credential_read",
        "blocked_credential_status",
    ],
    "category" => [
        "category_create",
        "category_update",
        "category_delete",
        "category_read",
        "category_status",
    ],
"terms" => [
        "terms_create",
        "terms_update",
        "terms_delete",
        "terms_read",
        "terms_status",
    ],
"payment_service" => [
        "payment_service_create",
        "payment_service_update",
        "payment_service_delete",
        "payment_service_read",
        "payment_service_status",
    ],
"payment" => [
        "payment_create",
        "payment_update",
        "payment_delete",
        "payment_read",
        "payment_status",
    ],
    "country" => [
        "country_create",
        "country_update",
        "country_delete",
        "country_read",
        "country_status",
    ],
    "city" => [
        "city_create",
        "city_update",
        "city_delete",
        "city_read",
        "city_status",
    ],
    "region" => [
        "region_create",
        "region_update",
        "region_delete",
        "region_read",
        "region_status",
    ],
    "subway" => [
        "subway_create",
        "subway_update",
        "subway_delete",
        "subway_read",
        "subway_status",
    ],
    "advertisement" => [
        "advertisement_create",
        "advertisement_update",
        "advertisement_delete",
        "advertisement_read",
        "advertisement_status",
    ],
];

return [
    "permissions" => $permissionArr,
    "roles" => [
        "user" => [],
        "admin" => $permissionArr,
    ]
];
